version: '3.8'

services:
  # Servicio de base de datos MariaDB
  mariadb:
    image: mariadb:latest
    environment:
      # Sin contraseña para root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: andaluciaskills
    ports:
      - "3307:3307"  # Mapeo de puerto correcto
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      # Modificado para no requerir contraseña
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de Backend Spring
  backend:
    build: ./backend
    ports:
      - "9005:9005"
    environment:
      # Corrección de la URL de conexión para MariaDB
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3307/andaluciaskills
      SPRING_DATASOURCE_USERNAME: root
      # Sin password
      SPRING_DATASOURCE_PASSWORD:
      SERVER_PORT: 9005
    depends_on:
      mariadb:
        condition: service_healthy
    # Red para asegurar comunicación
    networks:
      - app-network

  # Servicio de Frontend 
  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Puerto 80 para Nginx
    depends_on:
      - backend
    networks:
      - app-network

# Volumen para persistencia de datos de MariaDB
volumes:
  mysql_data:

# Red personalizada para los servicios
networks:
  app-network:
    driver: bridge